#!/bin/bash

function jormungandr-get-message-logs() {

  jcli rest v0 message logs

}

function jormungandr-get-message-logs-in-json() {

  jcli rest v0 message logs --output-format json

}

function jormungandr-get-txs-sent-from-local() {

  jormungandr-get-message-logs-in-json | jq '.[] | select(.received_from=="Rest")'

}

function jormungandr-get-txs-pending() {

  jormungandr-get-message-logs-in-json | jq '.[] | select(.status=="Pending")'

}

function jormungandr-get-account() {

  jcli rest v0 account get $1

}

function jormungandr-sk-to-pk() {

  echo $1 | jcli key to-public

}

function jormungandr-pk-to-address() {

  if [ -z "$DISCRIMINATION" ]
  then
    DISCRIMINATION="--testing"
  fi
  echo "Using '${DISCRIMINATION}' discrimination..."
  jcli address account $1

}

function jomrungandr-get-stats() {

  jcli rest v0 node stats get

}
