#!/bin/bash

function jormungandr-get-message-logs() {

  jcli rest v0 message logs

}

function jormungandr-get-message-logs-in-json() {

  jcli rest v0 message logs --output-format json

}

function jormungandr-get-txs-sent-from-local() {

  jormungandr-get-message-logs-in-json | jq '.[] | select(.received_from=="Rest")'

}

function jormungandr-get-txs-pending() {

  jormungandr-get-message-logs-in-json | jq '.[] | select(.status=="Pending")'

}

function jormungandr-get-account() {

  jcli rest v0 account get $1

}

function jormungandr-sk-to-pk() {

  echo $1 | jcli key to-public

}

function jormungandr-pk-to-address() {

  if [ -z "$DISCRIMINATION" ]
  then
    DISCRIMINATION="--testing"
  fi
  echo "Using '${DISCRIMINATION}' discrimination..." 1>&2
  jcli address account $1

}

function jormungandr-get-stats() {

  jcli rest v0 node stats get

}

# This one is courtesy of: https://github.com/ilap THANKS!
function jormungandr-get-network-info() {

  if [ -z "$*" ]
  then
    echo 'usage: jcr [API commands]
   - network stats: Network stats
   - network p2p view [blocks|fragments]: P2P View
   - network p2p available:
   - network tip: Tip
   - network p2p non_public: P2P non public nodes
   - network p2p quarantined: P2P quarantined nodes
   - or any API REST subcommands you are familiar with.' >&2
  else
    URL="${JORMUNGANDR_RESTAPI_URL:="http://localhost:${API_PORT:-3001}/api"}/v0"

    for i in $*
    do
     URL=${URL}"/${i}"
     shift
    done
    curl ${URL} 2>/dev/null  | jq '.'
  fi

}
